version: '3.5'

services:
  ids:
    container_name: ids
    hostname: ids
    build:
      context: ids/
      dockerfile: Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.18.0.2
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null

  scanner:
    container_name: scanner
    hostname: scanner
    ports:
      - "443:443"
      - "9390:9390"
    build:
      context: scanner/
      dockerfile: Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.18.0.3
    cap_add:
      - NET_ADMIN

  vulnerable:
    container_name: vulnerable
    hostname: vulnerable
    build:
      context: vulnerable/
      dockerfile: Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.18.0.4
    command: tail -f /dev/null

networks:
  internal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
